// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateWinProbability(arg1) {
  return window['go']['services']['CalculateService']['CalculateWinProbability'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['CalculateService']['SetContext'](arg1);
}
