// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CalculateWinProbability(arg1:services.SimulationRequest):Promise<services.SimulationResult>;

export function SetContext(arg1:context.Context):Promise<void>;
