// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCounts(arg1) {
  return window['go']['services']['ExportService']['ExportCounts'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['ExportService']['SetContext'](arg1);
}
