type Card = {
    rank: string;
    suit: string;
    id: string;
};

export const deck: Card[] = [
    { rank: 'A', suit: '♠️', id: 'A♠️' },
    { rank: 'A', suit: '♣️', id: 'A♣️' },
    { rank: 'A', suit: '♦️', id: 'A♦️' },
    { rank: 'A', suit: '❤︎', id: 'A❤︎' },
    { rank: 'K', suit: '♠️', id: 'K♠️' },
    { rank: 'K', suit: '♣️', id: 'K♣️' },
    { rank: 'K', suit: '♦️', id: 'K♦️' },
    { rank: 'K', suit: '❤︎', id: 'K❤︎' },
    { rank: 'Q', suit: '♠️', id: 'Q♠️' },
    { rank: 'Q', suit: '♣️', id: 'Q♣️' },
    { rank: 'Q', suit: '♦️', id: 'Q♦️' },
    { rank: 'Q', suit: '❤︎', id: 'Q❤︎' },
    { rank: 'J', suit: '♠️', id: 'J♠️' },
    { rank: 'J', suit: '♣️', id: 'J♣️' },
    { rank: 'J', suit: '♦️', id: 'J♦️' },
    { rank: 'J', suit: '❤︎', id: 'J❤︎' },
    { rank: 'T', suit: '♠️', id: 'T♠️' },
    { rank: 'T', suit: '♣️', id: 'T♣️' },
    { rank: 'T', suit: '♦️', id: 'T♦️' },
    { rank: 'T', suit: '❤︎', id: 'T❤︎' },
    { rank: '9', suit: '♠️', id: '9♠️' },
    { rank: '9', suit: '♣️', id: '9♣️' },
    { rank: '9', suit: '♦️', id: '9♦️' },
    { rank: '9', suit: '❤︎', id: '9❤︎' },
    { rank: '8', suit: '♠️', id: '8♠️' },
    { rank: '8', suit: '♣️', id: '8♣️' },
    { rank: '8', suit: '♦️', id: '8♦️' },
    { rank: '8', suit: '❤︎', id: '8❤︎' },
    { rank: '7', suit: '♠️', id: '7♠️' },
    { rank: '7', suit: '♣️', id: '7♣️' },
    { rank: '7', suit: '♦️', id: '7♦️' },
    { rank: '7', suit: '❤︎', id: '7❤︎' },
    { rank: '6', suit: '♠️', id: '6♠️' },
    { rank: '6', suit: '♣️', id: '6♣️' },
    { rank: '6', suit: '♦️', id: '6♦️' },
    { rank: '6', suit: '❤︎', id: '6❤︎' },
    { rank: '5', suit: '♠️', id: '5♠️' },
    { rank: '5', suit: '♣️', id: '5♣️' },
    { rank: '5', suit: '♦️', id: '5♦️' },
    { rank: '5', suit: '❤︎', id: '5❤︎' },
    { rank: '4', suit: '♠️', id: '4♠️' },
    { rank: '4', suit: '♣️', id: '4♣️' },
    { rank: '4', suit: '♦️', id: '4♦️' },
    { rank: '4', suit: '❤︎', id: '4❤︎' },
    { rank: '3', suit: '♠️', id: '3♠️' },
    { rank: '3', suit: '♣️', id: '3♣️' },
    { rank: '3', suit: '♦️', id: '3♦️' },
    { rank: '3', suit: '❤︎', id: '3❤︎' },
    { rank: '2', suit: '♠️', id: '2♠️' },
    { rank: '2', suit: '♣️', id: '2♣️' },
    { rank: '2', suit: '♦️', id: '2♦️' },
    { rank: '2', suit: '❤︎', id: '2❤︎' },
];